export interface KanaItem {
  id: string; // ID unik untuk state management (Pinia)
  character: string; // Karakter Jepang asli (あ / ア)
  romaji: string; // Cara baca standar
  rowGroup: string; // Pengelompokan baris (Vokal, K-Row, dst.)
}

export interface KanaGroup {
  gojuon: KanaItem[];
  dakuten: KanaItem[];
  yoon: KanaItem[];
}

export interface KanaData {
  hiragana: KanaGroup;
  katakana: KanaGroup;
}

export const kanaData: KanaData = {
  hiragana: {
    gojuon: [
      { id: "h-a", character: "あ", romaji: "A", rowGroup: "vowels" },
      { id: "h-i", character: "い", romaji: "I", rowGroup: "vowels" },
      { id: "h-u", character: "う", romaji: "U", rowGroup: "vowels" },
      { id: "h-e", character: "え", romaji: "E", rowGroup: "vowels" },
      { id: "h-o", character: "お", romaji: "O", rowGroup: "vowels" },
      { id: "h-ka", character: "か", romaji: "KA", rowGroup: "k" },
      { id: "h-ki", character: "き", romaji: "KI", rowGroup: "k" },
      { id: "h-ku", character: "く", romaji: "KU", rowGroup: "k" },
      { id: "h-ke", character: "け", romaji: "KE", rowGroup: "k" },
      { id: "h-ko", character: "こ", romaji: "KO", rowGroup: "k" },
      { id: "h-sa", character: "さ", romaji: "SA", rowGroup: "s" },
      { id: "h-shi", character: "し", romaji: "SHI", rowGroup: "s" },
      { id: "h-su", character: "す", romaji: "SU", rowGroup: "s" },
      { id: "h-se", character: "せ", romaji: "SE", rowGroup: "s" },
      { id: "h-so", character: "そ", romaji: "SO", rowGroup: "s" },
      { id: "h-ta", character: "た", romaji: "TA", rowGroup: "t" },
      { id: "h-chi", character: "ち", romaji: "CHI", rowGroup: "t" },
      { id: "h-tsu", character: "つ", romaji: "TSU", rowGroup: "t" },
      { id: "h-te", character: "て", romaji: "TE", rowGroup: "t" },
      { id: "h-to", character: "と", romaji: "TO", rowGroup: "t" },
      { id: "h-na", character: "な", romaji: "NA", rowGroup: "n" },
      { id: "h-ni", character: "に", romaji: "NI", rowGroup: "n" },
      { id: "h-nu", character: "ぬ", romaji: "NU", rowGroup: "n" },
      { id: "h-ne", character: "ね", romaji: "NE", rowGroup: "n" },
      { id: "h-no", character: "の", romaji: "NO", rowGroup: "n" },
      { id: "h-ha", character: "は", romaji: "HA", rowGroup: "h" },
      { id: "h-hi", character: "ひ", romaji: "HI", rowGroup: "h" },
      { id: "h-fu", character: "ふ", romaji: "FU", rowGroup: "h" },
      { id: "h-he", character: "へ", romaji: "HE", rowGroup: "h" },
      { id: "h-ho", character: "ほ", romaji: "HO", rowGroup: "h" },
      { id: "h-ma", character: "ま", romaji: "MA", rowGroup: "m" },
      { id: "h-mi", character: "み", romaji: "MI", rowGroup: "m" },
      { id: "h-mu", character: "む", romaji: "MU", rowGroup: "m" },
      { id: "h-me", character: "め", romaji: "ME", rowGroup: "m" },
      { id: "h-mo", character: "も", romaji: "MO", rowGroup: "m" },
      { id: "h-ya", character: "や", romaji: "YA", rowGroup: "y" },
      { id: "h-yu", character: "ゆ", romaji: "YU", rowGroup: "y" },
      { id: "h-yo", character: "よ", romaji: "YO", rowGroup: "y" },
      { id: "h-ra", character: "ら", romaji: "RA", rowGroup: "r" },
      { id: "h-ri", character: "り", romaji: "RI", rowGroup: "r" },
      { id: "h-ru", character: "る", romaji: "RU", rowGroup: "r" },
      { id: "h-re", character: "れ", romaji: "RE", rowGroup: "r" },
      { id: "h-ro", character: "ろ", romaji: "RO", rowGroup: "r" },
      {
        id: "h-wa",
        character: "わ",
        romaji: "WA",
        rowGroup: "w_single",
      },
      {
        id: "h-wo",
        character: "を",
        romaji: "WO",
        rowGroup: "w_single",
      },
      { id: "h-n", character: "ん", romaji: "N", rowGroup: "n_consonant" },
    ],
    dakuten: [
      { id: "h-ga", character: "が", romaji: "GA", rowGroup: "g" },
      { id: "h-gi", character: "ぎ", romaji: "GI", rowGroup: "g" },
      { id: "h-gu", character: "ぐ", romaji: "GU", rowGroup: "g" },
      { id: "h-ge", character: "げ", romaji: "GE", rowGroup: "g" },
      { id: "h-go", character: "ご", romaji: "GO", rowGroup: "g" },
      { id: "h-za", character: "ざ", romaji: "ZA", rowGroup: "z" },
      { id: "h-ji", character: "じ", romaji: "JI", rowGroup: "z" },
      { id: "h-zu", character: "ず", romaji: "ZU", rowGroup: "z" },
      { id: "h-ze", character: "ぜ", romaji: "ZE", rowGroup: "z" },
      { id: "h-zo", character: "ぞ", romaji: "ZO", rowGroup: "z" },
      { id: "h-da", character: "だ", romaji: "DA", rowGroup: "d" },
      { id: "h-dji", character: "ぢ", romaji: "JI", rowGroup: "d" },
      { id: "h-dzu", character: "づ", romaji: "ZU", rowGroup: "d" },
      { id: "h-de", character: "で", romaji: "DE", rowGroup: "d" },
      { id: "h-do", character: "ど", romaji: "DO", rowGroup: "d" },
      { id: "h-ba", character: "ば", romaji: "BA", rowGroup: "b" },
      { id: "h-bi", character: "び", romaji: "BI", rowGroup: "b" },
      { id: "h-bu", character: "ぶ", romaji: "BU", rowGroup: "b" },
      { id: "h-be", character: "べ", romaji: "BE", rowGroup: "b" },
      { id: "h-bo", character: "ぼ", romaji: "BO", rowGroup: "b" },
      { id: "h-pa", character: "ぱ", romaji: "PA", rowGroup: "p" },
      { id: "h-pi", character: "ぴ", romaji: "PI", rowGroup: "p" },
      { id: "h-pu", character: "ぷ", romaji: "PU", rowGroup: "p" },
      { id: "h-pe", character: "ぺ", romaji: "PE", rowGroup: "p" },
      { id: "h-po", character: "ぽ", romaji: "PO", rowGroup: "p" },
    ],
    yoon: [
      { id: "h-kya", character: "きゃ", romaji: "KYA", rowGroup: "k" },
      { id: "h-kyu", character: "きゅ", romaji: "KYU", rowGroup: "k" },
      { id: "h-kyo", character: "きょ", romaji: "KYO", rowGroup: "k" },
      { id: "h-gya", character: "ぎゃ", romaji: "GYA", rowGroup: "g" },
      { id: "h-gyu", character: "ぎゅ", romaji: "GYU", rowGroup: "g" },
      { id: "h-gyo", character: "ぎょ", romaji: "GYO", rowGroup: "g" },
      { id: "h-sha", character: "しゃ", romaji: "SHA", rowGroup: "s" },
      { id: "h-shu", character: "しゅ", romaji: "SHU", rowGroup: "s" },
      { id: "h-sho", character: "しょ", romaji: "SHO", rowGroup: "s" },
      { id: "h-ja", character: "じゃ", romaji: "JA", rowGroup: "z" },
      { id: "h-ju", character: "じゅ", romaji: "JU", rowGroup: "z" },
      { id: "h-jo", character: "じょ", romaji: "JO", rowGroup: "z" },
      { id: "h-cha", character: "ちゃ", romaji: "CHA", rowGroup: "t" },
      { id: "h-chu", character: "ちゅ", romaji: "CHU", rowGroup: "t" },
      { id: "h-cho", character: "ちょ", romaji: "CHO", rowGroup: "t" },
      { id: "h-nya", character: "にゃ", romaji: "NYA", rowGroup: "n" },
      { id: "h-nyu", character: "にゅ", romaji: "NYU", rowGroup: "n" },
      { id: "h-nyo", character: "にょ", romaji: "NYO", rowGroup: "n" },
      { id: "h-mya", character: "みゃ", romaji: "MYA", rowGroup: "m" },
      { id: "h-myu", character: "みゅ", romaji: "MYU", rowGroup: "m" },
      { id: "h-myo", character: "みょ", romaji: "MYO", rowGroup: "m" },
      { id: "h-rya", character: "りゃ", romaji: "RYA", rowGroup: "r" },
      { id: "h-ryu", character: "りゅ", romaji: "RYU", rowGroup: "r" },
      { id: "h-ryo", character: "りょ", romaji: "RYO", rowGroup: "r" },
      { id: "h-hya", character: "ひゃ", romaji: "HYA", rowGroup: "h" },
      { id: "h-hyu", character: "ひゅ", romaji: "HYU", rowGroup: "h" },
      { id: "h-hyo", character: "ひょ", romaji: "HYO", rowGroup: "h" },
      { id: "h-bya", character: "びゃ", romaji: "BYA", rowGroup: "b" },
      { id: "h-byu", character: "びゅ", romaji: "BYU", rowGroup: "b" },
      { id: "h-byo", character: "びょ", romaji: "BYO", rowGroup: "b" },
      { id: "h-pya", character: "ぴゃ", romaji: "PYA", rowGroup: "p" },
      { id: "h-pyu", character: "ぴゅ", romaji: "PYU", rowGroup: "p" },
      { id: "h-pyo", character: "ぴょ", romaji: "PYO", rowGroup: "p" },
    ],
  },
  katakana: {
    gojuon: [
      { id: "k-a", character: "ア", romaji: "A", rowGroup: "vowels" },
      { id: "k-i", character: "イ", romaji: "I", rowGroup: "vowels" },
      { id: "k-u", character: "ウ", romaji: "U", rowGroup: "vowels" },
      { id: "k-e", character: "エ", romaji: "E", rowGroup: "vowels" },
      { id: "k-o", character: "オ", romaji: "O", rowGroup: "vowels" },
      { id: "k-ka", character: "カ", romaji: "KA", rowGroup: "k" },
      { id: "k-ki", character: "キ", romaji: "KI", rowGroup: "k" },
      { id: "k-ku", character: "ク", romaji: "KU", rowGroup: "k" },
      { id: "k-ke", character: "ケ", romaji: "KE", rowGroup: "k" },
      { id: "k-ko", character: "コ", romaji: "KO", rowGroup: "k" },
      { id: "k-sa", character: "サ", romaji: "SA", rowGroup: "s" },
      { id: "k-shi", character: "シ", romaji: "SHI", rowGroup: "s" },
      { id: "k-su", character: "ス", romaji: "SU", rowGroup: "s" },
      { id: "k-se", character: "セ", romaji: "SE", rowGroup: "s" },
      { id: "k-so", character: "ソ", romaji: "SO", rowGroup: "s" },
      { id: "k-ta", character: "タ", romaji: "TA", rowGroup: "t" },
      { id: "k-chi", character: "チ", romaji: "CHI", rowGroup: "t" },
      { id: "k-tsu", character: "ツ", romaji: "TSU", rowGroup: "t" },
      { id: "k-te", character: "テ", romaji: "TE", rowGroup: "t" },
      { id: "k-to", character: "ト", romaji: "TO", rowGroup: "t" },
      { id: "k-na", character: "ナ", romaji: "NA", rowGroup: "n" },
      { id: "k-ni", character: "ニ", romaji: "NI", rowGroup: "n" },
      { id: "k-nu", character: "ヌ", romaji: "NU", rowGroup: "n" },
      { id: "k-ne", character: "ネ", romaji: "NE", rowGroup: "n" },
      { id: "k-no", character: "ノ", romaji: "NO", rowGroup: "n" },
      { id: "k-ha", character: "ハ", romaji: "HA", rowGroup: "h" },
      { id: "k-hi", character: "ヒ", romaji: "HI", rowGroup: "h" },
      { id: "k-fu", character: "フ", romaji: "FU", rowGroup: "h" },
      { id: "k-he", character: "ヘ", romaji: "HE", rowGroup: "h" },
      { id: "k-ho", character: "ホ", romaji: "HO", rowGroup: "h" },
      { id: "k-ma", character: "マ", romaji: "MA", rowGroup: "m" },
      { id: "k-mi", character: "ミ", romaji: "MI", rowGroup: "m" },
      { id: "k-mu", character: "ム", romaji: "MU", rowGroup: "m" },
      { id: "k-me", character: "メ", romaji: "ME", rowGroup: "m" },
      { id: "k-mo", character: "モ", romaji: "MO", rowGroup: "m" },
      { id: "k-ya", character: "ヤ", romaji: "YA", rowGroup: "y" },
      { id: "k-yu", character: "ユ", romaji: "YU", rowGroup: "y" },
      { id: "k-yo", character: "ヨ", romaji: "YO", rowGroup: "y" },
      { id: "k-ra", character: "ラ", romaji: "RA", rowGroup: "r" },
      { id: "k-ri", character: "リ", romaji: "RI", rowGroup: "r" },
      { id: "k-ru", character: "ル", romaji: "RU", rowGroup: "r" },
      { id: "k-re", character: "レ", romaji: "RE", rowGroup: "r" },
      { id: "k-ro", character: "ロ", romaji: "RO", rowGroup: "r" },
      {
        id: "k-wa",
        character: "ワ",
        romaji: "WA",
        rowGroup: "w_single",
      },
      {
        id: "k-wo",
        character: "ヲ",
        romaji: "WO",
        rowGroup: "w_single",
      },
      { id: "k-n", character: "ン", romaji: "N", rowGroup: "n_consonant" },
    ],
    dakuten: [
      { id: "k-ga", character: "ガ", romaji: "GA", rowGroup: "k_to_g" },
      { id: "k-gi", character: "ギ", romaji: "GI", rowGroup: "k_to_g" },
      { id: "k-gu", character: "グ", romaji: "GU", rowGroup: "k_to_g" },
      { id: "k-ge", character: "ゲ", romaji: "GE", rowGroup: "k_to_g" },
      { id: "k-go", character: "ゴ", romaji: "GO", rowGroup: "k_to_g" },
      { id: "k-za", character: "ザ", romaji: "ZA", rowGroup: "s_to_z" },
      { id: "k-ji", character: "ジ", romaji: "JI", rowGroup: "s_to_z" },
      { id: "k-zu", character: "ズ", romaji: "ZU", rowGroup: "s_to_z" },
      { id: "k-ze", character: "ゼ", romaji: "ZE", rowGroup: "s_to_z" },
      { id: "k-zo", character: "ゾ", romaji: "ZO", rowGroup: "s_to_z" },
      { id: "k-da", character: "ダ", romaji: "DA", rowGroup: "t_to_d" },
      { id: "k-dji", character: "ヂ", romaji: "JI", rowGroup: "t_to_d" },
      { id: "k-dzu", character: "ヅ", romaji: "ZU", rowGroup: "t_to_d" },
      { id: "k-de", character: "デ", romaji: "DE", rowGroup: "t_to_d" },
      { id: "k-do", character: "ド", romaji: "DO", rowGroup: "t_to_d" },
      {
        id: "k-ba",
        character: "バ",
        romaji: "BA",
        rowGroup: "h_to_b",
      },
      {
        id: "k-bi",
        character: "ビ",
        romaji: "BI",
        rowGroup: "h_to_b",
      },
      {
        id: "k-bu",
        character: "ブ",
        romaji: "BU",
        rowGroup: "h_to_b",
      },
      {
        id: "k-be",
        character: "ベ",
        romaji: "BE",
        rowGroup: "h_to_b",
      },
      {
        id: "k-bo",
        character: "ボ",
        romaji: "BO",
        rowGroup: "h_to_b",
      },
      {
        id: "k-pa",
        character: "パ",
        romaji: "PA",
        rowGroup: "h_to_p",
      },
      {
        id: "k-pi",
        character: "ピ",
        romaji: "PI",
        rowGroup: "h_to_p",
      },
      {
        id: "k-pu",
        character: "プ",
        romaji: "PU",
        rowGroup: "h_to_p",
      },
      {
        id: "k-pe",
        character: "ペ",
        romaji: "PE",
        rowGroup: "h_to_p",
      },
      {
        id: "k-po",
        character: "ポ",
        romaji: "PO",
        rowGroup: "h_to_p",
      },
    ],
    yoon: [
      // Klasik
      {
        id: "k-kya",
        character: "キャ",
        romaji: "KYA",
        rowGroup: "kg_classic",
      },
      {
        id: "k-kyu",
        character: "キュ",
        romaji: "KYU",
        rowGroup: "kg_classic",
      },
      {
        id: "k-kyo",
        character: "キョ",
        romaji: "KYO",
        rowGroup: "kg_classic",
      },
      {
        id: "k-gya",
        character: "ギャ",
        romaji: "GYA",
        rowGroup: "kg_classic",
      },
      {
        id: "k-gyu",
        character: "ギュ",
        romaji: "GYU",
        rowGroup: "kg_classic",
      },
      {
        id: "k-gyo",
        character: "ギョ",
        romaji: "GYO",
        rowGroup: "kg_classic",
      },
      {
        id: "k-sha",
        character: "シャ",
        romaji: "SHA",
        rowGroup: "sz_classic",
      },
      {
        id: "k-shu",
        character: "シュ",
        romaji: "SHU",
        rowGroup: "sz_classic",
      },
      {
        id: "k-sho",
        character: "ショ",
        romaji: "SHO",
        rowGroup: "sz_classic",
      },
      { id: "k-ja", character: "ジャ", romaji: "JA", rowGroup: "sz_classic" },
      { id: "k-ju", character: "ジュ", romaji: "JU", rowGroup: "sz_classic" },
      { id: "k-jo", character: "ジョ", romaji: "JO", rowGroup: "sz_classic" },
      {
        id: "k-cha",
        character: "チャ",
        romaji: "CHA",
        rowGroup: "td_classic",
      },
      {
        id: "k-chu",
        character: "チュ",
        romaji: "CHU",
        rowGroup: "td_classic",
      },
      {
        id: "k-cho",
        character: "チョ",
        romaji: "CHO",
        rowGroup: "td_classic",
      },
      {
        id: "k-dya",
        character: "ヂャ",
        romaji: "DYA",
        rowGroup: "td_classic",
      },
      {
        id: "k-dyu",
        character: "ヂュ",
        romaji: "DYU",
        rowGroup: "td_classic",
      },
      {
        id: "k-dyo",
        character: "ヂョ",
        romaji: "DYO",
        rowGroup: "td_classic",
      },
      {
        id: "k-nya",
        character: "ニャ",
        romaji: "NYA",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-nyu",
        character: "ニュ",
        romaji: "NYU",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-nyo",
        character: "ニョ",
        romaji: "NYO",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-mya",
        character: "ミャ",
        romaji: "MYA",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-myu",
        character: "ミュ",
        romaji: "MYU",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-myo",
        character: "ミョ",
        romaji: "MYO",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-rya",
        character: "リャ",
        romaji: "RYA",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-ryu",
        character: "リュ",
        romaji: "RYU",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-ryo",
        character: "リョ",
        romaji: "RYO",
        rowGroup: "nmr_classic",
      },
      {
        id: "k-hya",
        character: "ヒャ",
        romaji: "HYA",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-hyu",
        character: "ヒュ",
        romaji: "HYU",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-hyo",
        character: "ヒョ",
        romaji: "HYO",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-bya",
        character: "ビャ",
        romaji: "BYA",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-byu",
        character: "ビュ",
        romaji: "BYU",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-byo",
        character: "ビョ",
        romaji: "BYO",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-pya",
        character: "ピャ",
        romaji: "PYA",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-pyu",
        character: "ピュ",
        romaji: "PYU",
        rowGroup: "hbp_classic",
      },
      {
        id: "k-pyo",
        character: "ピョ",
        romaji: "PYO",
        rowGroup: "hbp_classic",
      },
      // Modern
      {
        id: "k-va",
        character: "ヴァ",
        romaji: "VA",
        rowGroup: "vw_modern",
      },
      {
        id: "k-vi",
        character: "ヴィ",
        romaji: "VI",
        rowGroup: "vw_modern",
      },
      {
        id: "k-ve",
        character: "ヴェ",
        romaji: "VE",
        rowGroup: "vw_modern",
      },
      {
        id: "k-vo",
        character: "ヴォ",
        romaji: "VO",
        rowGroup: "vw_modern",
      },
      {
        id: "k-wi",
        character: "ウィ",
        romaji: "WI",
        rowGroup: "vw_modern",
      },
      {
        id: "k-we",
        character: "ウェ",
        romaji: "WE",
        rowGroup: "vw_modern",
      },
      {
        id: "k-wo-m",
        character: "ウォ",
        romaji: "WO",
        rowGroup: "vw_modern",
      },
      {
        id: "k-fa",
        character: "ファ",
        romaji: "FA",
        rowGroup: "fts_modern",
      },
      {
        id: "k-fi",
        character: "フィ",
        romaji: "FI",
        rowGroup: "fts_modern",
      },
      {
        id: "k-fe",
        character: "フェ",
        romaji: "FE",
        rowGroup: "fts_modern",
      },
      {
        id: "k-fo",
        character: "フォ",
        romaji: "FO",
        rowGroup: "fts_modern",
      },
      {
        id: "k-tsa",
        character: "ツァ",
        romaji: "TSA",
        rowGroup: "fts_modern",
      },
      {
        id: "k-tsi",
        character: "ツィ",
        romaji: "TSI",
        rowGroup: "fts_modern",
      },
      {
        id: "k-tse",
        character: "ツェ",
        romaji: "TSE",
        rowGroup: "fts_modern",
      },
      {
        id: "k-tso",
        character: "ツォ",
        romaji: "TSO",
        rowGroup: "fts_modern",
      },
      {
        id: "k-she",
        character: "シェ",
        romaji: "SHE",
        rowGroup: "ei_vowel_modern",
      },
      {
        id: "k-je",
        character: "ジェ",
        romaji: "JE",
        rowGroup: "ei_vowel_modern",
      },
      {
        id: "k-che",
        character: "チェ",
        romaji: "CHE",
        rowGroup: "ei_vowel_modern",
      },
      {
        id: "k-twu",
        character: "トゥ",
        romaji: "TWU",
        rowGroup: "ei_vowel_modern",
      },
      {
        id: "k-ti",
        character: "ティ",
        romaji: "TI",
        rowGroup: "ei_vowel_modern",
      },
      {
        id: "k-dwu",
        character: "ドゥ",
        romaji: "DWU",
        rowGroup: "ei_vowel_modern",
      },
      {
        id: "k-di",
        character: "ディ",
        romaji: "DI",
        rowGroup: "ei_vowel_modern",
      },
    ],
  },
};
